# Generated by Django 4.0.2 on 2022-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_naumber', models.IntegerField(unique=True)),
                ('position', models.CharField(max_length=2, unique=True)),
                ('is_used', models.BooleanField()),
            ],
        ),
    ]
